name: ret
description: Tokenizes a string that represents a regular expression.
version: 0.0.1
homepage: https://github.com/Schwusch/ret

environment:
  sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.5
dependencies: 
  equatable: ^2.0.2
